import { Button, Form, Input, message } from 'antd'
import Head from 'next/head'
import { useApi } from '../../hooks/useApi';
import { authService } from '../../service/auth';
import style from './style.module.less'


export default function Login() {
  const [form] = Form.useForm();

  const { fetch, loading } = useApi(authService.login, { auto: false })

  const onFinish = (values: any) => {
    console.log(values);

    fetch(values).then((res) => {
      const data = res.data

      if (data.data.user) {
        message.success(`欢迎回来, ${data.data.user.name}`)
      }
      setTimeout(() => {
        window.location.href = '/'
      }, 1000);
    })
  };


  return <>
    <Head>
      <title>登录</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <div className={style.form}>

        <h3 className={style.form_title}>
          登录
        </h3>
        <Form size='large' form={form} onFinish={onFinish}>
          <Form.Item
            label="用户"
            name="name"
            rules={[{ required: true, message: 'Please input your username!' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="密码"
            name="password"
            rules={[{ required: true, message: 'Please input your password!' }]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item>
            <Button loading={loading} type="primary" block onClick={() => {
              form.submit()
            }}>Submit</Button>
          </Form.Item>
        </Form>
      </div>
    </main>
  </>
}